# code: language=ansible
---

- name: "Common | Repositories | Disable | Dnf / Yum"
  community.general.ini_file:
    path: "/etc/yum.repos.d/{{ item.file }}"
    section: "{{ item.name }}"
    option: "enabled"
    value: "0"
    mode: '0644'
  with_items: "{{ ansible_facts.repositories }}"
  when:
    - _common_repositories_disable_ is local.sys.list
    - item.name is defined
    - item.name in _common_repositories_disable_
    - item.state
  notify:
    - Update dnf cache
  become: true
  tags:
    - common
    - common-repositories
    - common-repositories-disable
