# code: language=ansible
---

- name: "Common | Sudo | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common.sudo.system.packages }}"
    state: present
    update_cache: false
  become: true
  tags:
    - common
    - common-sudo
    - common-sudo-install
