# code: language=ansible
---

- name: "Common"
  when:
    - roles.common | default(false)
  block:
    # 00 # Always
    - name: "Common | Always"
      ansible.builtin.include_tasks: "always/main.yml"
      tags:
        - always

    # 01 # Hostname
    - name: "Common | Hostname"
      ansible.builtin.include_tasks: "hostname/main.yml"
      when:
        - common.hostname | default('') is local.sys.str
      tags:
        - common
        - common-hostname

    # 02 # Hosts
    - name: "Common | Hosts"
      ansible.builtin.include_tasks: "hosts/main.yml"
      when:
        - common.hosts.data | default([]) is local.sys.list
        - common.hosts.data | length > common_defaults.hosts.data | length
      tags:
        - common
        - common-hosts

    # 03 # Timezone
    - name: "Common | Timezone"
      ansible.builtin.include_tasks: "timezone/main.yml"
      when:
        - common.timezone.name | default('') is local.sys.str
      tags:
        - common
        - common-timezone

    # 04 # Repositories
    - name: "Common | Repositories"
      ansible.builtin.include_tasks: "repositories/main.yml"
      when:
        - common.repositories | default({}) is local.sys.dict
        - common.repositories.manager[common_os.pkg] | default([]) is local.sys.list_dicts or
          common.repositories.enable | default([]) is local.sys.list or
          common.repositories.disable | default([]) is local.sys.list
      tags:
        - common
        - common-repositories
        - common-repositories-manager
        - common-repositories-add
        - common-repositories-gpg
        - common-repositories-enable
        - common-repositories-disable

    # 05 # Packages
    - name: "Common | Packages"
      ansible.builtin.include_tasks: "packages/main.yml"
      when:
        - common.packages is local.sys.dict
      tags:
        - common
        - common-packages

    # 06 # Locale
    - name: "Common | Locale"
      ansible.builtin.include_tasks: "locale/main.yml"
      when:
        - common.locale.name | default('') is local.sys.str
      tags:
        - common
        - common-locale

    # 07 # Users
    - name: "Common | Users"
      ansible.builtin.include_tasks: "users/main.yml"
      when:
        - common.users is local.sys.dict
      tags:
        - common
        - common-users

    # 08 # Sudo
    - name: "Common | Sudo"
      ansible.builtin.include_tasks: "sudo/main.yml"
      when:
        - common.sudo.groups | default({}) is local.sys.dict or
          common.sudo.users | default({}) is local.sys.dict
      tags:
        - common
        - common-sudo
        - common-sudo-install
        - common-sudo-configure

    # 09 # Dirs
    - name: "Common | Dirs"
      ansible.builtin.include_tasks: "dirs/main.yml"
      when:
        - common.dirs is local.sys.dict
      tags:
        - common
        - common-dirs

    # 10 # Environments
    - name: "Common | Environments"
      ansible.builtin.include_tasks: "environments/main.yml"
      when:
        - common.environments is local.sys.dict
      tags:
        - common
        - common-environments
