# code: language=ansible
---

- name: "Common | Repositories | Add | Dnf / Yum | GPG Keys"
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items: "{{ _common_repositories_add_ | selectattr('gpg', 'defined') |  map(attribute='gpg') | list | unique }}"
  when:
    - _common_repositories_add_ is local.sys.list_dicts
    - item is url
  become: true
  tags:
    - common
    - common-repositories
    - common-repositories-add
    - common-repositories-gpg

- name: "Common | Repositories | Dnf / Yum | Add repository"
  ansible.builtin.template:
    src: "repositories/dnf.repo.j2"
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: false
  with_items: "{{ _common_repositories_add_ }}"
  when:
    - _common_repositories_add_ is local.sys.list_dicts
  notify:
    - Update dnf cache
  become: true
  tags:
    - common
    - common-repositories
    - common-repositories-add
